[package]
name = "tauri-hasgard-fixture-app"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "tauri_hasgard_fixture_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
hasgard-testing = []

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-hasgard = { path = "../../../crates/tauri-plugin-hasgard" }
